# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_inf_chrom <- function(popSize, Hzero, maxTime, size_in_Morgan, markers, seed) {
    .Call('_isoSIM_sim_inf_chrom', PACKAGE = 'isoSIM', popSize, Hzero, maxTime, size_in_Morgan, markers, seed)
}

